### ISSUE TITLE
How can I reference the arguments?

### ISSUE THREAD

**Issue by justinmchase** [denoland/deno_task_shell#31]
Deno says that tasks accept task args:
```
> deno task --help
deno-task 
Run a task defined in the configuration file

  deno task build

USAGE:
    deno task [OPTIONS] [ARGS]

ARGS:
    <task>
            Task to be executed

    <task_args>...
            Additional arguments passed to the task
```

So I have a `deno.json` file like this:
```json
{
  "tasks": {
    "example": "echo \"Hello $1!\""
  }
}
```

And am invoking it like this and seeing weird output:
```
> deno task example Justin
Warning deno task is unstable and may drastically change in the future
Task example echo "Hello $1!" "Justin"
Hello ! Justin
```

Why is the arg printed out in the wrong spot and how can I reference it if not by `$1` ?

**Comment by justinmchase** [comment]
It seems like the answer is the in the second line of output:
```
Task example echo "Hello $1!" "Justin"
```

So I can use `printf` to format the last arg instead of echo:
```
{
  "tasks": {
    "example": "printf \"Hello %s!\""
  }
}
```

Which then looks like this:
```
Task example printf "Hello %s!" "justin"
```

I was definitely expecting it to pass the extra args as parameters to the whole script rather than just appending it as a string to the command...

It seems like it will be hard to do it this way once you start doing redirects and multiple expressions.

**Comment by dsherret** [comment]
@justinmchase yeah, the arguments get appended to the end of the command similar to how `npm run` works.

**Comment by harrysolovay** [comment]
I'm struggling to get this working. What might the `printf` equivalent of the following look like?

I initially tried

```json
  ...
  "build_wasm": "deno task run --unstable _tasks/build_wasm.ts --out 'bindings/${1}' --features='${1}'",
  "build_hashers_wasm": "deno task build_wasm hashers",
  ...
```

**Comment by dsherret** [comment]
@harrysolovay it only appends the arguments to the command. In those scenarios it's recommended to delegate that to a deno script. Basically anything complex should be relegated to a deno script and deno task is only intended for simple aliases.

Perhaps it would be good to add them as numbered variables to the shell state (ex. `$1`), but then probably we would probably still append the arguments to the end of the command. Appending arguments is a very common scenario and it doesn't look like `$@` is very user friendly (https://www.gnu.org/software/bash/manual/bash.html#Special-Parameters) because people would have to quote it to ensure it expands correctly (ex. `"$@"`).
