### ISSUE TITLE
[QUESTION] Why not use Rust coreutils?

### ISSUE THREAD

**Issue by dotnetCarpenter** [denoland/deno_task_shell#32]
Sorry, if this comes across as a "talk is cheap" or this has been discussed before (didn't see it in the closed issue list).

But why re-create [all the built-in commands](https://deno.land/manual@v1.20.1/tools/task_runner#built-in-commands), when they already exist as cross-platform Rust programs in https://docs.rs/crate/coreutils/0.0.13?

Would you be able to support every requests that has been here with `cargo build --features "cp mv rm mkdir pwd sleep echo cat" --no-default-features` (minus `xargs` and `exit`) and parse the `deno task` commands with Module [oursh](https://docs.rs/oursh/0.4.3/oursh/index.html)::[program](https://docs.rs/oursh/0.4.3/oursh/program/index.html)::[posix](https://docs.rs/oursh/0.4.3/oursh/program/posix/index.html#)?

Sorry, if you are having fun implemented these commands yet again, then you should absolutely continue the fun!

I am just curious to know if you are aware of existing Rust programs that does a similar thing and why you choose not to use them?

**Comment by dsherret** [comment]
Essentially, it's easier to get alignment with exactly what we want when we have full control over the functionality and it wasn't too bad to implement. In the case of `oursh` it has conditionals which we wouldn't add to deno task and it's missing a few things we would want (ex. pipes, subshells, quotes). It also creates some risk because you have to rely on decisions someone else makes about the future state of a project (ex. how would they implement globbing in the future and would that align with the glob functionality we want for deno task?). For deno task's current implementation, we can easily swap out any of the dependencies and still provide the same functionality to users.

For coreutils, I don't see a way to use each command that would take into account the state of the shell rather than the process. For example, `pwd` uses the global `env::current_dir()` (https://github.com/uutils/coreutils/blob/main/src/uu/pwd/src/pwd.rs), but our `pwd` command uses a non-global current working directory based on the current shell's state (ex. someone could start an asynchronous subshell that does a `cd` putting it into a different cwd than the process).

**Comment by dotnetCarpenter** [comment]
I guess non of the packages I found a really made to be used by other projects. Thank you for explaining the situation @dsherret :)
